### ISSUE TITLE
MS5611 access seems to require MPU6050 register setting

### ISSUE THREAD

**Issue by simondlevy** [simondlevy/BreezySTM32#3]
See examples/ms5611: comment out the XXX code and you can't read from the MS5611.

**Comment by superjax** [comment]
It turns out that it is not dependent upon the MPU6050 registers.  It just needs something to be written on the i2c port.   Check out the pull request I just submitted

**Comment by simondlevy** [comment]
Bravo, James!  I just merged your pull request.  As you note in your comment, having to do an I^2C write before detecting the MS5611 is still hard to explain, but it's a much more sensible hack than using the MPU6050 to detect the MS5611.
